project_id = "izxgyxqpgpcqvyzlwcgl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.bulletin-pricing-upload]
verify_jwt = false

[functions.generate-bulletin-template]
verify_jwt = false