// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izxgyxqpgpcqvyzlwcgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6eGd5eHFwZ3BjcXZ5emx3Y2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MTE3MDMsImV4cCI6MjA2ODE4NzcwM30.-Ov3oriA9KvlQf8VXovV-43g5N2xnTZ6YDxIaqpVQMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});